export interface DailyAyah {
  textArabic: string;
  textTranslation: string;
  surahName: string;
  surahNumber: number;
  ayahNumber: number;
  juzNumber: number;
}

export const DAILY_AYAHS: DailyAyah[] = [
  {
    textArabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
    textTranslation: 'In the name of Allah, the Most Gracious, the Most Merciful.',
    surahName: 'Al-Fatiha',
    surahNumber: 1,
    ayahNumber: 1,
    juzNumber: 1,
  },
  {
    textArabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۚ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۚ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۚ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    textTranslation: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness nor sleep overtakes Him. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass nothing of His knowledge except what He wills. His Kursi extends over the heavens and the earth, and their preservation does not tire Him. And He is the Most High, the Most Great.',
    surahName: 'Al-Baqarah',
    surahNumber: 2,
    ayahNumber: 255,
    juzNumber: 3,
  },
  {
    textArabic: 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ',
    textTranslation: 'Allah does not burden a soul more than it can bear. It will have what it earns, and it will bear what it earns.',
    surahName: 'Al-Baqarah',
    surahNumber: 2,
    ayahNumber: 286,
    juzNumber: 3,
  },
  {
    textArabic: 'إِنَّمَا أَمْرُهُ إِذَا أَرَادَ شَيْئًا أَنْ يَقُولَ لَهُ كُنْ فَيَكُونُ',
    textTranslation: 'His command, when He intends something, is only to say to it, "Be," and it is.',
    surahName: 'Ya-Sin',
    surahNumber: 36,
    ayahNumber: 82,
    juzNumber: 23,
  },
  {
    textArabic: 'فَبِمَا رَحْمَةٍ مِنَ اللَّهِ لِنْتَ لَهُمْ ۖ وَلَوْ كُنْتَ فَظًّا غَلِيظَ الْقَلْبِ لَانْفَضُّوا مِنْ حَوْلِكَ ۖ فَاعْفُ عَنْهُمْ وَاسْتَغْفِرْ لَهُمْ وَشَاوِرْهُمْ فِي الْأَمْرِ ۖ فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ ۚ إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ',
    textTranslation: 'So by mercy from Allah, you were gentle with them. And if you had been rude and harsh-hearted, they would have disbanded from around you. So pardon them, ask forgiveness for them, and consult them in the matter. And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely upon Him.',
    surahName: 'Aal-e-Imran',
    surahNumber: 3,
    ayahNumber: 159,
    juzNumber: 4,
  },
  {
    textArabic: 'كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ ۗ وَإِنَّمَا تُوَفَّوْنَ أُجُورَكُمْ يَوْمَ الْقِيَامَةِ ۖ فَمَنْ زُحْزِحَ عَنِ النَّارِ وَأُدْخِلَ الْجَنَّةَ فَقَدْ فَازَ ۗ وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ',
    textTranslation: 'Every soul will taste death. And you will only be given your full compensation on the Day of Resurrection. So whoever is drawn away from the Fire and admitted to Paradise has indeed attained. And what is the life of this world except the enjoyment of delusion.',
    surahName: 'Aal-e-Imran',
    surahNumber: 3,
    ayahNumber: 185,
    juzNumber: 4,
  },
  {
    textArabic: 'وَاعْبُدُوا اللَّهَ وَلَا تُشْرِكُوا بِهِ شَيْئًا ۖ وَبِالْوَالِدَيْنِ إِحْسَانًا وَبِذِي الْقُرْبَىٰ وَالْيَتَامَىٰ وَالْمَسَاكِينِ وَالْجَارِ ذِي الْقُرْبَىٰ وَالْجَارِ الْجُنُبِ وَالصَّاحِبِ بِالْجَنْبِ وَابْنِ السَّبِيلِ وَمَا مَلَكَتْ أَيْمَانُكُمْ',
    textTranslation: 'Worship Allah and associate nothing with Him, and to parents do good, and to relatives, orphans, the needy, the near neighbor, the distant neighbor, the companion at your side, the traveler, and those whom your right hands possess.',
    surahName: 'An-Nisa',
    surahNumber: 4,
    ayahNumber: 36,
    juzNumber: 5,
  },
  {
    textArabic: 'الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ وَأَتْمَمْتُ عَلَيْكُمْ نِعْمَتِي وَرَضِيتُ لَكُمُ الْإِسْلَامَ دِينًا',
    textTranslation: 'This day I have perfected for you your religion and completed My favor upon you and have approved for you Islam as religion.',
    surahName: 'Al-Ma\'idah',
    surahNumber: 5,
    ayahNumber: 3,
    juzNumber: 6,
  },
  {
    textArabic: 'قُلْ إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ رَبِّ الْعَالَمِينَ . لَا شَرِيكَ لَهُ ۖ وَبِذَٰلِكَ أُمِرْتُ وَأَنَا أَوَّلُ الْمُسْلِمِينَ',
    textTranslation: 'Say, "Indeed, my prayer, my rites, my living and my dying are for Allah, Lord of the worlds. No partner has He. And this I have been commanded, and I am the first of the Muslims."',
    surahName: 'Al-An\'am',
    surahNumber: 6,
    ayahNumber: 162,
    juzNumber: 8,
  },
  {
    textArabic: 'خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ وَأَعْرِضْ عَنِ الْجَاهِلِينَ',
    textTranslation: 'Take what is given freely, enjoin what is good, and turn away from the ignorant.',
    surahName: 'Al-A\'raf',
    surahNumber: 7,
    ayahNumber: 199,
    juzNumber: 9,
  },
  {
    textArabic: 'إِنَّمَا يَعْمُرُ مَسَاجِدَ اللَّهِ مَنْ آمَنَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ وَأَقَامَ الصَّلَاةَ وَآتَى الزَّكَاةَ وَلَمْ يَخْشَ إِلَّا اللَّهَ ۖ فَعَسَىٰ أُولَٰئِكَ أَنْ يَكُونُوا مِنَ الْمُهْتَدِينَ',
    textTranslation: 'The mosques of Allah are only to be maintained by those who believe in Allah and the Last Day, establish prayer, give zakah, and fear none but Allah. It is those who are expected to be among the guided.',
    surahName: 'At-Tawbah',
    surahNumber: 9,
    ayahNumber: 18,
    juzNumber: 10,
  },
  {
    textArabic: 'يَا أَيُّهَا النَّاسُ قَدْ جَاءَتْكُمْ مَوْعِظَةٌ مِنْ رَبِّكُمْ وَشِفَاءٌ لِمَا فِي الصُّدُورِ وَهُدًى وَرَحْمَةٌ لِلْمُؤْمِنِينَ',
    textTranslation: 'O mankind, there has come to you instruction from your Lord and healing for what is in the chests, and guidance and mercy for the believers.',
    surahName: 'Yunus',
    surahNumber: 10,
    ayahNumber: 57,
    juzNumber: 11,
  },
  {
    textArabic: 'وَمَا مِنْ دَابَّةٍ فِي الْأَرْضِ إِلَّا عَلَى اللَّهِ رِزْقُهَا وَيَعْلَمُ مُسْتَقَرَّهَا وَمُسْتَوْدَعَهَا ۚ كُلٌّ فِي كِتَابٍ مُبِينٍ',
    textTranslation: 'And there is no creature on earth but that upon Allah is its provision, and He knows its dwelling place and its resting place. All is in a clear register.',
    surahName: 'Hud',
    surahNumber: 11,
    ayahNumber: 6,
    juzNumber: 12,
  },
  {
    textArabic: 'يَا بَنِيَّ اذْهَبُوا فَتَحَسَّسُوا مِنْ يُوسُفَ وَأَخِيهِ وَلَا تَيْأَسُوا مِنْ رَوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِنْ رَوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ',
    textTranslation: 'O my sons, go and inquire about Joseph and his brother and do not despair of the mercy of Allah. Indeed, no one despairs of the mercy of Allah except the disbelieving people.',
    surahName: 'Yusuf',
    surahNumber: 12,
    ayahNumber: 87,
    juzNumber: 13,
  },
  {
    textArabic: 'الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُمْ بِذِكْرِ اللَّهِ ۗ أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
    textTranslation: 'Those who have believed and whose hearts are assured by the remembrance of Allah. Unquestionably, by the remembrance of Allah hearts are assured.',
    surahName: 'Ar-Ra\'d',
    surahNumber: 13,
    ayahNumber: 28,
    juzNumber: 13,
  },
  {
    textArabic: 'وَإِذْ تَأَذَّنَ رَبُّكُمْ لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُمْ ۖ وَلَئِنْ كَفَرْتُمْ إِنَّ عَذَابِي لَشَدِيدٌ',
    textTranslation: 'And when your Lord proclaimed, "If you are grateful, I will surely increase you; but if you deny, indeed, My punishment is severe."',
    surahName: 'Ibrahim',
    surahNumber: 14,
    ayahNumber: 7,
    juzNumber: 13,
  },
  {
    textArabic: 'إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ وَإِنَّا لَهُ لَحَافِظُونَ',
    textTranslation: 'Indeed, it is We who sent down the Reminder and indeed, We will be its guardian.',
    surahName: 'Al-Hijr',
    surahNumber: 15,
    ayahNumber: 9,
    juzNumber: 14,
  },
  {
    textArabic: 'ادْعُ إِلَىٰ سَبِيلِ رَبِّكَ بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ ۖ وَجَادِلْهُمْ بِالَّتِي هِيَ أَحْسَنُ ۚ إِنَّ رَبَّكَ هُوَ أَعْلَمُ بِمَنْ ضَلَّ عَنْ سَبِيلِهِ ۖ وَهُوَ أَعْلَمُ بِالْمُهْتَدِينَ',
    textTranslation: 'Invite to the way of your Lord with wisdom and good instruction, and argue with them in a way that is best. Indeed, your Lord knows who has strayed from His way, and He knows who are guided.',
    surahName: 'An-Nahl',
    surahNumber: 16,
    ayahNumber: 125,
    juzNumber: 14,
  },
  {
    textArabic: 'وَقَضَىٰ رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا ۚ إِمَّا يَبْلُغَنَّ عِنْدَكَ الْكِبَرَ أَحَدُهُمَا أَوْ كِلَاهُمَا فَلَا تَقُلْ لَهُمَا أُفٍّ وَلَا تَنْهَرْهُمَا وَقُلْ لَهُمَا قَوْلًا كَرِيمًا',
    textTranslation: 'Your Lord has decreed that you worship none but Him and be dutiful to your parents. If one or both of them reach old age with you, do not say to them "uff" nor repel them, but speak to them a noble word.',
    surahName: 'Al-Isra',
    surahNumber: 17,
    ayahNumber: 23,
    juzNumber: 15,
  },
  {
    textArabic: 'قُلْ إِنَّمَا أَنَا بَشَرٌ مِثْلُكُمْ يُوحَىٰ إِلَيَّ أَنَّمَا إِلَٰهُكُمْ إِلَٰهٌ وَاحِدٌ ۖ فَمَنْ كَانَ يَرْجُو لِقَاءَ رَبِّهِ فَلْيَعْمَلْ عَمَلًا صَالِحًا وَلَا يُشْرِكْ بِعِبَادَةِ رَبِّهِ أَحَدًا',
    textTranslation: 'Say, "I am only a man like you, revealed to me that your god is one God. So whoever hopes for the meeting with his Lord, let him do righteous work and not associate anyone in the worship of his Lord."',
    surahName: 'Al-Kahf',
    surahNumber: 18,
    ayahNumber: 110,
    juzNumber: 16,
  },
  {
    textArabic: 'اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ ۚ مَثَلُ نُورِهِ كَمِشْكَاةٍ فِيهَا مِصْبَاحٌ ۖ الْمِصْبَاحُ فِي زُجَاجَةٍ ۖ الزُّجَاجَةُ كَأَنَّهَا كَوْكَبٌ دُرِّيٌّ يُوقَدُ مِنْ شَجَرَةٍ مُبَارَكَةٍ زَيْتُونَةٍ لَا شَرْقِيَّةٍ وَلَا غَرْبِيَّةٍ يَكَادُ زَيْتُهَا يُضِيءُ وَلَوْ لَمْ تَمْسَسْهُ نَارٌ ۚ نُورٌ عَلَىٰ نُورٍ ۚ يَهْدِي اللَّهُ لِنُورِهِ مَنْ يَشَاءُ',
    textTranslation: 'Allah is the Light of the heavens and the earth. The example of His light is like a niche within which is a lamp, the lamp within glass, the glass as if it were a pearly star lit from a blessed olive tree, neither of the east nor of the west, whose oil would almost glow even if untouched by fire. Light upon light. Allah guides to His light whom He wills.',
    surahName: 'An-Nur',
    surahNumber: 24,
    ayahNumber: 35,
    juzNumber: 18,
  },
  {
    textArabic: 'وَعِبَادُ الرَّحْمَٰنِ الَّذِينَ يَمْشُونَ عَلَى الْأَرْضِ هَوْنًا وَإِذَا خَاطَبَهُمُ الْجَاهِلُونَ قَالُوا سَلَامًا',
    textTranslation: 'The servants of the Most Merciful are those who walk upon the earth in modesty, and when the ignorant address them, they say words of peace.',
    surahName: 'Al-Furqan',
    surahNumber: 25,
    ayahNumber: 63,
    juzNumber: 19,
  },
  {
    textArabic: 'أَمَّنْ يُجِيبُ الْمُضْطَرَّ إِذَا دَعَاهُ وَيَكْشِفُ السُّوءَ وَيَجْعَلُكُمْ خُلَفَاءَ الْأَرْضِ ۗ أَإِلَٰهٌ مَعَ اللَّهِ ۚ قَلِيلًا مَا تَذَكَّرُونَ',
    textTranslation: 'Is He who responds to the desperate one when he calls upon Him and removes evil and makes you successors of the earth? Is there a god with Allah? Little do you remember.',
    surahName: 'An-Naml',
    surahNumber: 27,
    ayahNumber: 62,
    juzNumber: 20,
  },
  {
    textArabic: 'وَابْتَغِ فِيمَا آتَاكَ اللَّهُ الدَّارَ الْآخِرَةَ ۖ وَلَا تَنْسَ نَصِيبَكَ مِنَ الدُّنْيَا ۖ وَأَحْسِنْ كَمَا أَحْسَنَ اللَّهُ إِلَيْكَ ۖ وَلَا تَبْغِ الْفَسَادَ فِي الْأَرْضِ ۖ إِنَّ اللَّهَ لَا يُحِبُّ الْمُفْسِدِينَ',
    textTranslation: 'Seek, through that which Allah has given you, the home of the Hereafter, and do not forget your share of the world. And do good as Allah has done good to you, and do not seek corruption in the land. Indeed, Allah does not like corrupters.',
    surahName: 'Al-Qasas',
    surahNumber: 28,
    ayahNumber: 77,
    juzNumber: 20,
  },
  {
    textArabic: 'وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا ۚ وَإِنَّ اللَّهَ لَمَعَ الْمُحْسِنِينَ',
    textTranslation: 'Those who strive for Us — We will surely guide them to Our ways. And indeed, Allah is with the doers of good.',
    surahName: 'Al-Ankabut',
    surahNumber: 29,
    ayahNumber: 69,
    juzNumber: 21,
  },
  {
    textArabic: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ',
    textTranslation: 'Say, "O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Oft-Forgiving, the Most Merciful."',
    surahName: 'Az-Zumar',
    surahNumber: 39,
    ayahNumber: 53,
    juzNumber: 24,
  },
  {
    textArabic: 'وَمَا خَلَقْتُ الْجِنَّ وَالْإِنْسَ إِلَّا لِيَعْبُدُونِ',
    textTranslation: 'I did not create jinn and mankind except to worship Me.',
    surahName: 'Adh-Dhariyat',
    surahNumber: 51,
    ayahNumber: 56,
    juzNumber: 27,
  },
  {
    textArabic: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا . إِنَّ مَعَ الْعُسْرِ يُسْرًا',
    textTranslation: 'For indeed, with hardship comes ease. Indeed, with hardship comes ease.',
    surahName: 'Ash-Sharh',
    surahNumber: 94,
    ayahNumber: 5,
    juzNumber: 30,
  },
  {
    textArabic: 'فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ . وَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ',
    textTranslation: 'Whoever does an atom\'s weight of good will see it, and whoever does an atom\'s weight of evil will see it.',
    surahName: 'Az-Zalzalah',
    surahNumber: 99,
    ayahNumber: 7,
    juzNumber: 30,
  },
  {
    textArabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ . اللَّهُ الصَّمَدُ . لَمْ يَلِدْ وَلَمْ يُولَدْ . وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    textTranslation: 'Say, "He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent."',
    surahName: 'Al-Ikhlas',
    surahNumber: 112,
    ayahNumber: 1,
    juzNumber: 30,
  },
];
